---
apiVersion: v1
kind: Secret
metadata:
  name: example-vpn-bind-creds
type: Opaque
data:
  bind-dn: KIT_BIND_DN
  bind-pw: KIT_BIND_PW
---
apiVersion: brain.cloudflinger.com/v1alpha1
kind: Openvpn
metadata:
  name: foxpass-vpn
  labels:
    app: openvpn
spec:
  # Values for openvpn.
  replicaCount: 1
  updateStrategy: {}
  exporter:
    enabled: false
    image:
      repository: cloudflinger/openvpn-exporter
      tag: 1.0.0
      pullPolicy: IfNotPresent
  image:
    repository: cloudflinger/openvpn-ldap
    tag: 1.0.0
    pullPolicy: IfNotPresent
  service:
    type: LoadBalancer
    externalPort: 443
    internalPort: 443
    LoadBalancerSourceRanges: 0.0.0.0/0
    annotations:
      external-dns.alpha.kubernetes.io/hostname: vpn.example.com.
  resources:
    limits:
      cpu: 300m
      memory: 128Mi
    requests:
      cpu: 300m
      memory: 128Mi
  persistence:
    enabled: true
    storageClass: "standard"
    accessMode: ReadWriteOnce
    size: 2M
  openvpn:
    ldap:
      bindCredsSecretName: example-vpn-bind-creds
      enabled: true
      url: "ldaps://ldap.foxpass.com"
      baseDN: "KIT_BASE_DN"
      searchFilter: "(&(uid=%u))"
    # Network allocated for openvpn clients
    OVPN_NETWORK: KIT_OVPN_NETWORK
    # Network subnet allocated for openvpn client
    OVPN_SUBNET: KIT_OVPN_SUBNET
    # Protocol used by openvpn
    OVPN_PROTO: tcp
    OVPN_DNS_NAME: "KIT_EXTERNAL_FQDN"
    # Kubernetes pod network
    OVPN_K8S_POD_NETWORK: "KIT_OVPN_K8S_POD_NETWORK"
    OVPN_K8S_POD_SUBNET: "KIT_OVPN_K8S_POD_SUBNET"
    # Kubernetes service network
    OVPN_K8S_CLUSTER_IP_NETWORK: "KIT_OVPN_K8S_CLUSTER_IP_NETWORK"
    OVPN_K8S_CLUSTER_IP_SUBNET: "KIT_OVPN_K8S_CLUSTER_IP_SUBNET"
    # Kubernetes node ip network
    OVPN_K8S_NODE_NETWORK: "KIT_OVPN_K8S_NODE_NETWORK"
    OVPN_K8S_NODE_SUBNET: "KIT_OVPN_K8S_NODE_SUBNET"
    # TODO: idk if we want this or not
    dhcpOptionDomain: false
    redirectGateway: false
    # Arbitrary lines appended to the end of the server configuration file
    # conf: |
    #  max-clients 100
    #  client-to-client
